services:
  web:
    build: .
    ports:
      - "8080:80"
      - "9003:9003"  # Port pour Xdebug
    volumes:
      - ${APP_PATH:-./app}:/var/www/app
      - ./.env:/var/www/app/.env
      - ./.env.local:/var/www/app/.env.local
      - ./.env.dev:/var/www/app/.env.dev
      - ./.env.test:/var/www/app/.env.test
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - APP_SECRET=${APP_SECRET}
      - APP_DEBUG=${APP_DEBUG:-1}
      - DATABASE_URL=${DATABASE_URL}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-256M}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE:-64M}
      - POST_MAX_SIZE=${POST_MAX_SIZE:-64M}
      - APP_PATH=${APP_PATH:-./app}
      - PUBLIC_PATH=${PUBLIC_PATH:-./app/public}
      - VAR_PATH=${VAR_PATH:-./app/var}
      - VENDOR_PATH=${VENDOR_PATH:-./app/vendor}
      - PHP_IDE_CONFIG=serverName=symfony
      - XDEBUG_MODE=debug,develop
      - XDEBUG_CONFIG="client_host=host.docker.internal"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 