symfonycasts_reset_password:
  # Durée de validité du token en secondes (1 heure = 3600 secondes)
  lifetime: 3600
  # Intervalle minimum entre deux demandes de réinitialisation pour un même utilisateur (en secondes)
  throttle_limit: 3600
  # Le service qui sera utilisé pour gérer la collecte des anciens tokens
  enable_garbage_collection: true
  # Le service qui sera utilisé pour stocker les tokens
  request_password_repository: App\Repository\ResetPasswordRequestRepository
